# Generated by Django 5.1 on 2024-08-30 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        ('requirements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='requirements',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='requirements.requirements'),
        ),
    ]
